### ISSUE TITLE
Documentation seems to be out of date.

### ISSUE THREAD

**Issue by joprice** [soundcloud/pipeline-generator#2]
There seems to be a few out of date or missing details in the docs:

* "clone this project from git into..." - this first instruction doesn't say where to clone into. Newcomers to go projects might not know what to do. 
* "adjust the file Pipeline" - there doesn't seem to be a file by this name
* "./ppl-example create test-pipeline" - I also can't find a file by this name

**Comment by kesselborn** [comment]
thanks for this report!
Wil fix this.
Cheers,
